/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:fbd5ab0b8b7743965a0aadcb70007c25:8494b77a6bf6a58b78d6bec10f07351f:3b001db8b4d74db621bb79e8a54d0600$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Test
	{
		public const string Rabite_01 = "rabite_01";
		public const string Rabite_02 = "rabite_02";
		public const string Rabite_03 = "rabite_03";
		public const string Rabite_04 = "rabite_04";
		public const string Rabite_05 = "rabite_05";
		public const string Rabite_06 = "rabite_06";
		public const string Rabite_07 = "rabite_07";
		public const string Rabite_08 = "rabite_08";
		public const string Rabite_09 = "rabite_09";
		public const string Rabite_10 = "rabite_10";
		public const string Rabite_11 = "rabite_11";
		public const string Rabite_12 = "rabite_12";
		public const string Rabite_13 = "rabite_13";
		public const string Rabite_14 = "rabite_14";
		public const string Rabite_15 = "rabite_15";
		public const string Rabite_16 = "rabite_16";
		public const string Rabite_17 = "rabite_17";
		public const string Rabite_18 = "rabite_18";
		public const string Rabite_19 = "rabite_19";
		public const string Rabite_20 = "rabite_20";
		public const string Rabite_21 = "rabite_21";
		public const string Rabite_22 = "rabite_22";
		public const string Rabite_23 = "rabite_23";
	}
}